name: async_preferences_example
description: Demonstrates how to use the async_preferences plugin.
publish_to: 'none'

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  async_preferences:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 2.6.1

flutter:
  uses-material-design: true